steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: 'build'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      projects: '**/*Tests*/*.csproj'
      arguments: '--configuration $(BuildConfiguration) --logger trx --collect "Code coverage"'

  - task: PublishTestResults@2
    displayName: Publish Code-coverage
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '*.trx' 
      searchFolder: '$(Agent.TempDirectory)'
      failTaskOnFailedTests: true
      publishRunAttachments: true

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: True
      arguments: '--configuration $(BuildConfiguration) --output "$(Build.ArtifactStagingDirectory)"'
      zipAfterPublish: True

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'


